# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
    name: github
    repo: musikele/blog-eleventy

media_folder: /images
public_folder: /images

collections:
    - name: posts
      label: Posts
      folder: _posts
      slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
      sortable_fields: [title, date]
      summary: "{{date | date('YYYY-MM-DD')}} | {{title}} |  Bozza: {{eleventyExcludeFromCollections}}"
      fields:
          - { label: Title, name: title, widget: string }
          - { label: Date, name: date, widget: datetime, default: '{{now}}' }
          - { label: Layout, name: layout, widget: hidden, default: 'post' }
          - { label: Description, name: description, widget: text, required: false }
          - { label: Permalink, name: permalink, widget: string, required: false }
          - {
                label: Draft,
                name: eleventyExcludeFromCollections,
                widget: boolean,
                default: true,
                required: false,
            }
          - {
                label: Tags,
                name: tags,
                widget: list,
                required: false,
                field: { label: Tag, name: tag, widget: string },
            }
          - { label: Header Image, name: headerImg, widget: image, required: false }
          - { label: Body, name: body, widget: markdown }
