# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: musikele/blog-eleventy

media_folder: /images
public_folder: /

collections:
  - name: posts
    label: Posts
    folder: _posts
    sortable_fields: [title, date]
    summary: "{{date | date('YYYY-MM-DD')}} | {{title}} |  Bozza: {{eleventyExcludeFromCollections}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime, default: "{{now}}" }
      - { label: Description, name: description, widget: text, required: false }
      - { label: Permalink, name: permalink, widget: string, required: false }
      - { label: Draft, name: eleventyExcludeFromCollections, widget: boolean, default: true, required: false }
      - { label: Tags, name: tags, widget: list, required: false }
      - { label: Header Image, name: headerImg, widget: image, required: true }
      - { label: Body, name: body, widget: markdown }
    